language: go
dist: bionic
sudo: required
# update (it's not done by default)
before_install:
  - sudo apt-get update
  - sudo apt-get install -y wget 
go:
  - 1.13
script:
  - go build hello.go
  - bash test-hello.sh